// jsonData.js

let json = `
[
  {
    "id":1,
    "first_name":"Celine",
    "last_name":"O'Harney",
    "email":"coharney0@bbc.co.uk",
    "gender":"Female",
    "salary":5133
  },
  {
    "id":2,
    "first_name":"Rene",
    "last_name":"Slayton",
    "email":"rslayton1@usa.gov",
    "gender":"Male",
    "salary":3882
  },
  {
    "id":3,
    "first_name":"Tamas",
    "last_name":"Druhan",
    "email":"tdruhan2@deviantart.com",
    "gender":"Male",
    "salary":6206
  },
  {
    "id":4,
    "first_name":"Cullan",
    "last_name":"Carrabot",
    "email":"ccarrabot3@booking.com",
    "gender":"Male",
    "salary":8611
  },
  {
    "id":5,
    "first_name":"Blondelle",
    "last_name":"Lumbers",
    "email":"blumbers4@webs.com",
    "gender":"Female",
    "salary":3008
  },
  {
    "id":6,
    "first_name":"Glyn",
    "last_name":"Boult",
    "email":"gboult5@comcast.net",
    "gender":"Male",
    "salary":5638
  },
  {
    "id":7,
    "first_name":"Carlyn",
    "last_name":"Durram",
    "email":"cdurram6@usnews.com",
    "gender":"Bigender",
    "salary":4280
  },
  {
    "id":8,
    "first_name":"Adoree",
    "last_name":"Peller",
    "email":"apeller7@t.co",
    "gender":"Female",
    "salary":5185
  },
  {
    "id":9,
    "first_name":"Quinton",
    "last_name":"Boothebie",
    "email":"qboothebie8@instagram.com",
    "gender":"Male",
    "salary":7325
  },
  {
    "id":10,
    "first_name":"Quinta",
    "last_name":"Matias",
    "email":"qmatias9@bigcartel.com",
    "gender":"Female",
    "salary":7985
  },
  {
    "id":11,
    "first_name":"Roi",
    "last_name":"McCully",
    "email":"rmccullya@abc.net.au",
    "gender":"Male",
    "salary":8368
  },
  {
    "id":12,
    "first_name":"Suzie",
    "last_name":"Worster",
    "email":"sworsterb@scientificamerican.com",
    "gender":"Female",
    "salary":6300
  },
  {
    "id":13,
    "first_name":"Baxie",
    "last_name":"Derington",
    "email":"bderingtonc@hexun.com",
    "gender":"Male",
    "salary":3518
  },
  {
    "id":14,
    "first_name":"Hadlee",
    "last_name":"Avarne",
    "email":"havarned@globo.com",
    "gender":"Male",
    "salary":7017
  },
  {
    "id":15,
    "first_name":"Bernadine",
    "last_name":"Payler",
    "email":"bpaylere@npr.org",
    "gender":"Female",
    "salary":7086
  },
  {
    "id":16,
    "first_name":"Bobby",
    "last_name":"Beccero",
    "email":"bbeccerof@trellian.com",
    "gender":"Male",
    "salary":2564
  },
  {
    "id":17,
    "first_name":"Efren",
    "last_name":"Nowlan",
    "email":"enowlang@boston.com",
    "gender":"Male",
    "salary":4271
  },
  {
    "id":18,
    "first_name":"Nial",
    "last_name":"Joint",
    "email":"njointh@tinypic.com",
    "gender":"Male",
    "salary":7284
  },
  {
    "id":19,
    "first_name":"Theo",
    "last_name":"Gawke",
    "email":"tgawkei@amazon.co.jp",
    "gender":"Female",
    "salary":8169
  },
  {
    "id":20,
    "first_name":"Torrence",
    "last_name":"Parkyns",
    "email":"tparkynsj@yale.edu",
    "gender":"Male",
    "salary":6505
  }
]`;